---
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: rabbitmq_user.yml

- name: checking to see if already clustered
  stat: path=/etc/rabbitmq/clustered
  register: clustered

- name: rabbitmq_clustering.yml
  when: enable_rabbitmq_clustering and (clustered.stat.exists != True)
  
