---
- name: rabbitmq_user | create user 
  rabbitmq_user: user= {{ rabbitmq_user }} password={{ rabbitmq_password }} vhost=/ configure_priv=.* read_priv=.* write_priv=.* tags=adminstration state=present 
